package com.start.boot.email.webService;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * cesMessageService service = new cesMessageService();
 * MessageServiceImpDelegate portType = service.getCesMessage();
 * portType.addMessage(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "cesMessageService", targetNamespace = "http://webService/", wsdlLocation = "file:/C:/workspace/zfxtpt_177/web/wsdl/cesMessageService.wsdl")
public class CesMessageService extends Service {

	private final static URL CESMESSAGESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(CesMessageService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = CesMessageService.class.getResource(".");
			url = new URL(
					baseUrl,
					"file:/C:/workspace/zfxtpt_177/web/wsdl/cesMessageService.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/workspace/zfxtpt_177/web/wsdl/cesMessageService.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CESMESSAGESERVICE_WSDL_LOCATION = url;
	}

	public CesMessageService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CesMessageService() {
		super(CESMESSAGESERVICE_WSDL_LOCATION, new QName("http://webService/",
				"cesMessageService"));
	}

	/**
	 * 
	 * @return returns MessageServiceImpDelegate
	 */
	@WebEndpoint(name = "cesMessage")
	public MessageServiceImpDelegate getCesMessage() {
		return super.getPort(new QName("http://webService/", "cesMessage"),
				MessageServiceImpDelegate.class);
	}

}
