package com.start.boot.email.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MessageServiceImpDelegate", targetNamespace = "http://webService/")
public interface MessageServiceImpDelegate {

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 * @param arg7
	 * @param arg8
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "addMessage", targetNamespace = "http://webService/", className = "webService.AddMessage")
	@ResponseWrapper(localName = "addMessageResponse", targetNamespace = "http://webService/", className = "webService.AddMessageResponse")
	public String addMessage(
            @WebParam(name = "arg0", targetNamespace = "") long arg0,
            @WebParam(name = "arg1", targetNamespace = "") String arg1,
            @WebParam(name = "arg2", targetNamespace = "") String arg2,
            @WebParam(name = "arg3", targetNamespace = "") String arg3,
            @WebParam(name = "arg4", targetNamespace = "") String arg4,
            @WebParam(name = "arg5", targetNamespace = "") String arg5,
            @WebParam(name = "arg6", targetNamespace = "") String arg6,
            @WebParam(name = "arg7", targetNamespace = "") long arg7,
            @WebParam(name = "arg8", targetNamespace = "") String arg8);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "addMessageSend", targetNamespace = "http://webService/", className = "webService.AddMessageSend")
	@ResponseWrapper(localName = "addMessageSendResponse", targetNamespace = "http://webService/", className = "webService.AddMessageSendResponse")
	public void addMessageSend(
            @WebParam(name = "arg0", targetNamespace = "") long arg0,
            @WebParam(name = "arg1", targetNamespace = "") long arg1,
            @WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @return returns java.util.List<webService.WotalkMessage>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getWotalkMessage", targetNamespace = "http://webService/", className = "webService.GetWotalkMessage")
	@ResponseWrapper(localName = "getWotalkMessageResponse", targetNamespace = "http://webService/", className = "webService.GetWotalkMessageResponse")
	public List<WotalkMessage> getWotalkMessage();

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateWotalkMessageType", targetNamespace = "http://webService/", className = "webService.UpdateWotalkMessageType")
	@ResponseWrapper(localName = "updateWotalkMessageTypeResponse", targetNamespace = "http://webService/", className = "webService.UpdateWotalkMessageTypeResponse")
	public String updateWotalkMessageType(
            @WebParam(name = "arg0", targetNamespace = "") List<String> arg0);

}
